# This is a basic workflow to help you get started with Actions

name: Testing workflow variables

# Controls when the workflow will run
on:
  workflow_dispatch:

env:
  cloud: google_cloud

jobs:
  greeting_jobs:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "say hello name is Monday"
        run: echo "$Greeting $first_name is using $cloud"
        env:
          first_name: vishal
      
  
